//
//  Users.swift
//  GitHubSearchUsersTests
//
//  Created by Aurora on 29.08.24.
//

import Foundation

struct Users {
    let users = """
    {
     "total_count": 10,
     "incomplete_results": false,
     "items": [
         {
             "login": "asdfeq",
             "id": 25857874,
             "node_id": "MDEyOk9yZ2FuaXphdGlvbjI1ODU3ODc0",
             "avatar_url": "https://avatars.githubusercontent.com/u/25857874?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeq",
             "html_url": "https://github.com/asdfeq",
             "followers_url": "https://api.github.com/users/asdfeq/followers",
             "following_url": "https://api.github.com/users/asdfeq/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeq/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeq/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeq/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeq/orgs",
             "repos_url": "https://api.github.com/users/asdfeq/repos",
             "events_url": "https://api.github.com/users/asdfeq/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeq/received_events",
             "type": "Organization",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeqve",
             "id": 129252223,
             "node_id": "U_kgDOB7Q7fw",
             "avatar_url": "https://avatars.githubusercontent.com/u/129252223?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeqve",
             "html_url": "https://github.com/asdfeqve",
             "followers_url": "https://api.github.com/users/asdfeqve/followers",
             "following_url": "https://api.github.com/users/asdfeqve/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeqve/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeqve/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeqve/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeqve/orgs",
             "repos_url": "https://api.github.com/users/asdfeqve/repos",
             "events_url": "https://api.github.com/users/asdfeqve/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeqve/received_events",
             "type": "User",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "Asdfeqqwwe",
             "id": 130311421,
             "node_id": "U_kgDOB8Rk_Q",
             "avatar_url": "https://avatars.githubusercontent.com/u/130311421?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/Asdfeqqwwe",
             "html_url": "https://github.com/Asdfeqqwwe",
             "followers_url": "https://api.github.com/users/Asdfeqqwwe/followers",
             "following_url": "https://api.github.com/users/Asdfeqqwwe/following{/other_user}",
             "gists_url": "https://api.github.com/users/Asdfeqqwwe/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/Asdfeqqwwe/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/Asdfeqqwwe/subscriptions",
             "organizations_url": "https://api.github.com/users/Asdfeqqwwe/orgs",
             "repos_url": "https://api.github.com/users/Asdfeqqwwe/repos",
             "events_url": "https://api.github.com/users/Asdfeqqwwe/events{/privacy}",
             "received_events_url": "https://api.github.com/users/Asdfeqqwwe/received_events",
             "type": "User",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeqwefg",
             "id": 152747021,
             "node_id": "U_kgDOCRq8DQ",
             "avatar_url": "https://avatars.githubusercontent.com/u/152747021?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeqwefg",
             "html_url": "https://github.com/asdfeqwefg",
             "followers_url": "https://api.github.com/users/asdfeqwefg/followers",
             "following_url": "https://api.github.com/users/asdfeqwefg/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeqwefg/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeqwefg/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeqwefg/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeqwefg/orgs",
             "repos_url": "https://api.github.com/users/asdfeqwefg/repos",
             "events_url": "https://api.github.com/users/asdfeqwefg/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeqwefg/received_events",
             "type": "User",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeqwr",
             "id": 52279533,
             "node_id": "MDEyOk9yZ2FuaXphdGlvbjUyMjc5NTMz",
             "avatar_url": "https://avatars.githubusercontent.com/u/52279533?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeqwr",
             "html_url": "https://github.com/asdfeqwr",
             "followers_url": "https://api.github.com/users/asdfeqwr/followers",
             "following_url": "https://api.github.com/users/asdfeqwr/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeqwr/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeqwr/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeqwr/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeqwr/orgs",
             "repos_url": "https://api.github.com/users/asdfeqwr/repos",
             "events_url": "https://api.github.com/users/asdfeqwr/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeqwr/received_events",
             "type": "Organization",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeqwe",
             "id": 112910308,
             "node_id": "U_kgDOBrrf5A",
             "avatar_url": "https://avatars.githubusercontent.com/u/112910308?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeqwe",
             "html_url": "https://github.com/asdfeqwe",
             "followers_url": "https://api.github.com/users/asdfeqwe/followers",
             "following_url": "https://api.github.com/users/asdfeqwe/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeqwe/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeqwe/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeqwe/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeqwe/orgs",
             "repos_url": "https://api.github.com/users/asdfeqwe/repos",
             "events_url": "https://api.github.com/users/asdfeqwe/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeqwe/received_events",
             "type": "User",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeqd",
             "id": 168968445,
             "node_id": "U_kgDOChJA_Q",
             "avatar_url": "https://avatars.githubusercontent.com/u/168968445?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeqd",
             "html_url": "https://github.com/asdfeqd",
             "followers_url": "https://api.github.com/users/asdfeqd/followers",
             "following_url": "https://api.github.com/users/asdfeqd/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeqd/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeqd/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeqd/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeqd/orgs",
             "repos_url": "https://api.github.com/users/asdfeqd/repos",
             "events_url": "https://api.github.com/users/asdfeqd/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeqd/received_events",
             "type": "User",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeqwd",
             "id": 65728069,
             "node_id": "MDQ6VXNlcjY1NzI4MDY5",
             "avatar_url": "https://avatars.githubusercontent.com/u/65728069?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeqwd",
             "html_url": "https://github.com/asdfeqwd",
             "followers_url": "https://api.github.com/users/asdfeqwd/followers",
             "following_url": "https://api.github.com/users/asdfeqwd/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeqwd/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeqwd/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeqwd/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeqwd/orgs",
             "repos_url": "https://api.github.com/users/asdfeqwd/repos",
             "events_url": "https://api.github.com/users/asdfeqwd/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeqwd/received_events",
             "type": "User",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeqw",
             "id": 42986094,
             "node_id": "MDEyOk9yZ2FuaXphdGlvbjQyOTg2MDk0",
             "avatar_url": "https://avatars.githubusercontent.com/u/42986094?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeqw",
             "html_url": "https://github.com/asdfeqw",
             "followers_url": "https://api.github.com/users/asdfeqw/followers",
             "following_url": "https://api.github.com/users/asdfeqw/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeqw/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeqw/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeqw/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeqw/orgs",
             "repos_url": "https://api.github.com/users/asdfeqw/repos",
             "events_url": "https://api.github.com/users/asdfeqw/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeqw/received_events",
             "type": "Organization",
             "site_admin": false,
             "score": 1.0
         },
         {
             "login": "asdfeq123",
             "id": 178002602,
             "node_id": "U_kgDOCpwaqg",
             "avatar_url": "https://avatars.githubusercontent.com/u/178002602?v=4",
             "gravatar_id": "",
             "url": "https://api.github.com/users/asdfeq123",
             "html_url": "https://github.com/asdfeq123",
             "followers_url": "https://api.github.com/users/asdfeq123/followers",
             "following_url": "https://api.github.com/users/asdfeq123/following{/other_user}",
             "gists_url": "https://api.github.com/users/asdfeq123/gists{/gist_id}",
             "starred_url": "https://api.github.com/users/asdfeq123/starred{/owner}{/repo}",
             "subscriptions_url": "https://api.github.com/users/asdfeq123/subscriptions",
             "organizations_url": "https://api.github.com/users/asdfeq123/orgs",
             "repos_url": "https://api.github.com/users/asdfeq123/repos",
             "events_url": "https://api.github.com/users/asdfeq123/events{/privacy}",
             "received_events_url": "https://api.github.com/users/asdfeq123/received_events",
             "type": "User",
             "site_admin": false,
             "score": 1.0
         }
     ]
 }
"""
}
